/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Moment: (() => {
      const tableId = new TableId("", "Moment");
      return defineComponent(
        world,
        {
          date: RecsType.BigInt,
          startTime: RecsType.BigInt,
          endTime: RecsType.BigInt,
          isLive: RecsType.Boolean,
          owner: RecsType.String,
          location: RecsType.String,
          locationType: RecsType.String,
          title: RecsType.String,
          description: RecsType.String,
          nftMetadata: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    CheckIn: (() => {
      const tableId = new TableId("", "CheckIn");
      return defineComponent(
        world,
        {
          momentId: RecsType.String,
          blockNumber: RecsType.BigInt,
          wallet: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
