// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Moment, MomentData, MomentTableId } from "./tables/Moment.sol";
import { CheckIn, CheckInData, CheckInTableId } from "./tables/CheckIn.sol";
