// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMomentSystem {
  function createMoment(
    string memory location,
    string memory locationType,
    uint64 date,
    uint64 startTime,
    uint64 endTime,
    bool isLive,
    string memory title,
    string memory description,
    string memory nftMetadata
  ) external;

  function toggleIsLive(bytes32 momentId) external;
}
