// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMomentSystem {
  function createMoment(
    uint64 date,
    uint64 startTime,
    uint64 endTime,
    bool isLive,
    string memory owner,
    string memory location,
    string memory title,
    string memory description,
    string memory nftMetadata
  ) external returns (bool);

  function toggleIsLive(bytes32 momentId) external returns (bool);
}
